# Form implementation generated from reading ui file 'devEUI_window.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(475, 469)
        self.Select_DevEUI_label = QtWidgets.QLabel(parent=Form)
        self.Select_DevEUI_label.setGeometry(QtCore.QRect(60, 50, 111, 17))
        self.Select_DevEUI_label.setObjectName("Select_DevEUI_label")
        self.ok_button_DevEUI = QtWidgets.QPushButton(parent=Form)
        self.ok_button_DevEUI.setGeometry(QtCore.QRect(180, 390, 101, 31))
        self.ok_button_DevEUI.setObjectName("ok_button_DevEUI")
        self.By_default_label = QtWidgets.QLabel(parent=Form)
        self.By_default_label.setGeometry(QtCore.QRect(110, 100, 81, 17))
        self.By_default_label.setObjectName("By_default_label")
        self.checkBox_devEUI = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_devEUI.setGeometry(QtCore.QRect(160, 130, 181, 23))
        self.checkBox_devEUI.setObjectName("checkBox_devEUI")
        self.lineEdit_devEUI = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_devEUI.setGeometry(QtCore.QRect(110, 210, 271, 25))
        self.lineEdit_devEUI.setObjectName("lineEdit_devEUI")
        self.Enter_devEUI_label = QtWidgets.QLabel(parent=Form)
        self.Enter_devEUI_label.setGeometry(QtCore.QRect(110, 170, 101, 17))
        self.Enter_devEUI_label.setObjectName("Enter_devEUI_label")
        self.check_device_label = QtWidgets.QLabel(parent=Form)
        self.check_device_label.setGeometry(QtCore.QRect(60, 270, 261, 17))
        self.check_device_label.setObjectName("check_device_label")
        self.check_button = QtWidgets.QPushButton(parent=Form)
        self.check_button.setGeometry(QtCore.QRect(320, 260, 101, 31))
        self.check_button.setObjectName("check_button")
        self.output_label = QtWidgets.QLabel(parent=Form)
        self.output_label.setGeometry(QtCore.QRect(60, 320, 371, 17))
        self.output_label.setObjectName("output_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Select_DevEUI_label.setText(_translate("Form", "Select DevEUI :"))
        self.ok_button_DevEUI.setText(_translate("Form", "ok"))
        self.By_default_label.setText(_translate("Form", "By default :"))
        self.checkBox_devEUI.setText(_translate("Form", "    20635FACAB000144"))
        self.Enter_devEUI_label.setText(_translate("Form", "Enter DevEUI :"))
        self.check_device_label.setText(_translate("Form", "Check device connected to the port :"))
        self.check_button.setText(_translate("Form", "check"))
        self.output_label.setText(_translate("Form", "output :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
